### ISSUE TITLE
klue dependency

### ISSUE THREAD

**Issue by dfporter** [fairliereese/igvf_pipeline#1]
The klue dependency appears to no longer be available. Do you have an alternative solution or a copy of the klue code? Thank you!

**Comment by fairliereese** [comment]
Hi there, klue is still being actively developed and is in a private repo at the moment. 
Aside from that though, I am curious what your use case for this pipeline is. The workflow and input data format is pretty specific to the lab's experimental design, but if you're interested maybe I can point you to some more general rules you could borrow to make your own pipeline.

**Comment by dfporter** [comment]
I have data similar to the Parse kits but do not have access to their software for analysis (bought the reagents ourselves instead of buying a kit), so I did a search for snakemake pipelines that would process that type of data. Finding this repo, I edited it to work with our custom barcodes and got to the kallisto h5ad outputs where klue would kick in. 

Mouse genotype quantification from mixed well inputs isn't our use case but I wanted to see how the pipeline handled that because it seemed one could use that approach for QC (e.g., seeing if cells from the wrong subject were in the wrong wells) - but I suspect I misunderstood what the klue step was doing. I would be interested in more general Parse-type data workflows you could point me to. Perhaps there is a more general open source snakemake for Parse-type data you'd recommend?

**Comment by fairliereese** [comment]
Oh super, this is a great use case. Unfortunately I'm not involved with the klue project, but your proposed use of it for QC might be helpful when it's eventually out. I managed to find an old version of the workflow when I was still developing the pipeline that doesn't use klue [here](https://github.com/mortazavilab/parse_pipeline/blob/76b4d5ff031a9969760081ec73d36954e15e68b3/snakemake/Snakefile_no_klue). I'm sure there will be minutiae you'll have to change but maybe this can help circumvent the klue step until it comes out.

**Comment by dfporter** [comment]
Thank you! I appreciate it.

**Comment by Charles-Alexandre-Roy** [comment]
I am also interested in using this pipeline without the `klue` dependency. However, @fairliereese the "Snakefile_no_klue" file you pointed to above has an entire section called "klue" with multiple rules that seem to use it. @dfporter were you able to get this to work and if so, would you be willing to share the Snakefile you prepared?

Super grateful for any help with this!
